version: '3'

services:

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}

    ports:
      - 127.0.0.1:${LOCAL_DB_PORT}:5432

    volumes:
      - db-data:/var/lib/postgresql/data
      - ./${BACKUP_DIR}:/db_dump 

  app:
    container_name: "flask_app_postgre"
    restart: always
    image: olegdavimuka/lesson_project
    environment:
      - FLASK_ENV=production
      - FLASK_APP=wsgi:app
      - FLASK_DEBUG=1
      - FLASK_PORT=${FLASK_PORT}
    ports:
      - 127.0.0.1:9191:${FLASK_PORT}
    entrypoint: "bash entry-point.sh"

    depends_on:
      - db

  celery_worker:
    container_name: "celery_worker"
    restart: always
    image: olegdavimuka/lesson_project
    depends_on:
      - db
    command: >
      celery -A worker worker -B --loglevel=INFO  

  redis:
    restart: always
    image: redis:alpine
    ports:
      - 127.0.0.1:${REDIS_PORT}:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >
      --requirepass ${REDIS_PASSWORD}
    
volumes:
  db-data:
  db_dump:

