"""empty message

Revision ID: 1b8beb68aa6f
Revises: c7d90ce047bd
Create Date: 2022-04-22 11:35:31.561860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8beb68aa6f'
down_revision = 'c7d90ce047bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username2', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username2')
    # ### end Alembic commands ###
