"""empty message

Revision ID: 965a055f12fe
Revises: c1df3c198017
Create Date: 2022-04-26 11:26:52.747288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965a055f12fe'
down_revision = 'c1df3c198017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username2', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username2')
    # ### end Alembic commands ###
