name: Lesson for CI
on: [push, pull_request]
jobs:
 test_job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Python install
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - name: Install Python Poetry
              uses: abatilo/actions-poetry@v2.1.0
              with:
                poetry-version: 1.1.2
            - name: Configure poetry
              shell: bash
                run: python -m poetry config virtualenvs.in-project true
            - name: Install dependencies
              run: |
                python -m poetry install
            - name: Lint with flake8
              run: |
                python -m poetry run flake8 . --count  --show-source --statistics
            - name: Test with pytest
              run: |
                python -m poetry run pytest

